### ISSUE TITLE
장소 검색

### ISSUE THREAD

**Issue by Bang71** [RavenousCoders/ravenousgps-ios#2]
## Description

손쉬운 목적지 선택을 위한 검색 기능 작업입니다.

## Tasks
- [ ] SPM으로 Google Place SDK for iOS 설치 및 import
- [ ] Search Bar 레이아웃 작업
- [ ] Place API를 통해 검색된 위치의 좌표 획득
- [ ] 해당 좌표로 지도 위치 이동 작업
