### ISSUE TITLE
알림 기능

### ISSUE THREAD

**Issue by Bang71** [RavenousCoders/ravenousgps-ios#7]
## Description

기준 거리에 도달한 목적지에 대해 알림을 제공하는 작업입니다.

## Tasks
- [ ] 백그라운드에서도 알림을 수신하도록 Info.plist 파일을 설정합니다
- [ ] UserNotifications 프레임워크를 import 합니다
- [ ] AppDelegate에서 발송된 Notifications 에 대한 처리 방법을 작성합니다
- [ ] 목적지를 선택하는 단계에서 알림 권한을 요청합니다
- [ ] 실시간 위치, 목적지 위치가 기준 거리 이내에 해당하면 Notification을 발송합니다
